[tools]
"aqua:aws-sso" = "latest"
"cargo:jwt-cli" = "latest"
"npm:@ast-grep/cli" = "latest"
"npm:knip" = "latest"
"npm:serve" = "latest"
bat = "latest"
deno = "latest"
difftastic = "latest"
gh = "latest"
jq = "latest"
node = "lts"
python = "3.13"
rclone = "latest"
rust = "latest"
shellcheck = "latest"
uv = "latest"
yq = "latest"
