[tools]
"aqua:aws-sso" = "latest"
"cargo:jwt-cli" = "latest"
"npm:@ast-grep/cli" = "latest"
"npm:knip" = "latest"
"npm:serve" = "latest"
"pipx:httpie" = "latest"
bat = "latest"
colima = "latest"
deno = "latest"
difftastic = "latest"
gh = "latest"
jq = "latest"
lima = "latest"
node = "lts"
python = "3.13"
rclone = "latest"
rust = "latest"
shellcheck = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"

[settings]
disable_backends = ["asdf"]

[settings.pipx]
uvx = true
