[tools]
"npm:knip" = "latest"
"npm:serve" = "latest"
"pipx:httpie" = "latest"
ast-grep = "latest"
bat = "latest"
deno = "latest"
difftastic = "latest"
fd = "latest"
gh = "latest"
hyperfine = "latest"
jq = "latest"
node = "lts"
python = "latest"
rclone = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
ubi = "latest"
uv = "latest"
yq = "latest"

[settings]
disable_backends = ["asdf"]
idiomatic_version_file_enable_tools = ["python", "node"]

[settings.pipx]
uvx = true
